services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=24
        - NGINX_VERSION=1.27.5
    ports:
      - "80:80"
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    