services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - NGINX_VERSION=${NGINX_VERSION}
    ports:
      - "8080:80"
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    