services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_VERSION=3.9.9-eclipse-temurin-21
        - JDK_VERSION=21
    ports:
      - "8080:80"
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    