name: Maven CI (Run for All Projects)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Find All Projects
        id: find_projects
        run: |
          projects=$(find . -maxdepth 1 -type d -name "ca*" | sed 's|^\./||' | jq -R -s -c 'split("\n")[:-1]')
          echo "projects=$projects" >> $GITHUB_ENV
          echo "::set-output name=projects::$projects"

  build-matrix:
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.build-test.outputs.projects) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test ${{ matrix.project }}
        run: |
          cd ${{ matrix.project }}
          mvn clean install
